"""Agregar modulo presupuestos

Revision ID: 6a8f7f05760f
Revises: 
Create Date: 2026-01-27 13:54:08.473913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a8f7f05760f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presupuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('cliente_nombre', sa.String(length=100), nullable=True),
    sa.Column('cliente_telefono', sa.String(length=20), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descuento_porcentaje', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('descuento_monto', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aceptado', 'rechazado', 'vencido', 'convertido', name='estado_presupuesto'), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('presupuestos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presupuestos_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presupuestos_numero'), ['numero'], unique=False)
        batch_op.create_index(batch_op.f('ix_presupuestos_token'), ['token'], unique=True)

    op.create_table('presupuesto_detalles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('presupuesto_detalles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presupuesto_detalles_presupuesto_id'), ['presupuesto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presupuesto_detalles_producto_id'), ['producto_id'], unique=False)

    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('presupuesto_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ventas_presupuesto_id'), ['presupuesto_id'], unique=False)
        batch_op.create_foreign_key(None, 'presupuestos', ['presupuesto_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ventas_presupuesto_id'))
        batch_op.drop_column('presupuesto_id')

    with op.batch_alter_table('presupuesto_detalles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presupuesto_detalles_producto_id'))
        batch_op.drop_index(batch_op.f('ix_presupuesto_detalles_presupuesto_id'))

    op.drop_table('presupuesto_detalles')
    with op.batch_alter_table('presupuestos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presupuestos_token'))
        batch_op.drop_index(batch_op.f('ix_presupuestos_numero'))
        batch_op.drop_index(batch_op.f('ix_presupuestos_cliente_id'))

    op.drop_table('presupuestos')
    # ### end Alembic commands ###
